### ISSUE TITLE
Using

### ISSUE THREAD

**Issue by Wern-rm** [zzsort/monono2#7]
Please tell me how to use the program and how to compile it correctly .geo files?

**Comment by zzsort** [comment]
run ALGeoBuilder.exe:
ALGeoBuilder.exe -geo -o c:\geo_files_output_here c:\your_aion_client_dir

Here is some info for hooking up the .geo files that may be useful:
https://github.com/zzsort/monono2/issues/1

**Comment by Wern-rm** [comment]
> run ALGeoBuilder.exe:
> ALGeoBuilder.exe -geo -o c:\geo_files_output_here c:\your_aion_client_dir
> 
> Here is some info for hooking up the .geo files that may be useful:
> #1

And which files should I take from the client? And refer to them, please tell me...

**Comment by Wern-rm** [comment]
Error...

`    [210050000] - (12/165) - LF4 ...
      Parsing leveldata.xml ...
System.FormatException: Входная строка имела неверный формат.
   в System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   в System.Single.Parse(String s)
   в monono2.Common.LevelDataXmlLoader.LoadWaterLevel(XDocument xdoc) в D:\Git\monono2\Common\FileFormats\LevelDataXmlLoader.cs:строка 48
   в monono2.Common.LevelDataXmlLoader.Load(Stream levelDataXml) в D:\Git\monono2\Common\FileFormats\LevelDataXmlLoader.cs:строка 33
   в monono2.Common.LevelDataXmlLoader..ctor(Stream levelDataXml) в D:\Git\monono2\Common\FileFormats\LevelDataXmlLoader.cs:строка 26
   в monono2.ALGeoBuilder.AionLevelsProcessor.Process() в D:\Git\monono2\ALGeoBuilder\AionLevelsProcessor.cs:строка 262
   в monono2.ALGeoBuilder.Program.Main(String[] args) в D:\Git\monono2\ALGeoBuilder\Program.cs:строка 70`

**Comment by Wern-rm** [comment]
Aion 4.8 version

**Comment by Wern-rm** [comment]
Will there be support for versions below 5. x?

**Comment by Wern-rm** [comment]
fixed!
